//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class tmx {
    
    private header headerField;
    
    private tu[] bodyField;
    
    private string versionField;
    
    public tmx() {
        this.versionField = "1.4";
    }
    
    /// <remarks/>
    public header header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("tu", IsNullable=false)]
    public tu[] body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class header {
    
    private object[] itemsField;
    
    private string creationtoolField;
    
    private string creationtoolversionField;
    
    private headerSegtype segtypeField;
    
    private string otmfField;
    
    private string adminlangField;
    
    private string srclangField;
    
    private string datatypeField;
    
    private string oencodingField;
    
    private string creationdateField;
    
    private string creationidField;
    
    private string changedateField;
    
    private string changeidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note", typeof(note))]
    [System.Xml.Serialization.XmlElementAttribute("prop", typeof(prop))]
    [System.Xml.Serialization.XmlElementAttribute("ude", typeof(ude))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationtool {
        get {
            return this.creationtoolField;
        }
        set {
            this.creationtoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationtoolversion {
        get {
            return this.creationtoolversionField;
        }
        set {
            this.creationtoolversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public headerSegtype segtype {
        get {
            return this.segtypeField;
        }
        set {
            this.segtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-tmf")]
    public string otmf {
        get {
            return this.otmfField;
        }
        set {
            this.otmfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string adminlang {
        get {
            return this.adminlangField;
        }
        set {
            this.adminlangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string srclang {
        get {
            return this.srclangField;
        }
        set {
            this.srclangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-encoding")]
    public string oencoding {
        get {
            return this.oencodingField;
        }
        set {
            this.oencodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationdate {
        get {
            return this.creationdateField;
        }
        set {
            this.creationdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationid {
        get {
            return this.creationidField;
        }
        set {
            this.creationidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changedate {
        get {
            return this.changedateField;
        }
        set {
            this.changedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changeid {
        get {
            return this.changeidField;
        }
        set {
            this.changeidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class note {
    
    private string oencodingField;
    
    private string langField;
    
    private string lang1Field;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-encoding")]
    public string oencoding {
        get {
            return this.oencodingField;
        }
        set {
            this.oencodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("lang")]
    public string lang1 {
        get {
            return this.lang1Field;
        }
        set {
            this.lang1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class prop {
    
    private string typeField;
    
    private string langField;
    
    private string oencodingField;
    
    private string lang1Field;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-encoding")]
    public string oencoding {
        get {
            return this.oencodingField;
        }
        set {
            this.oencodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("lang")]
    public string lang1 {
        get {
            return this.lang1Field;
        }
        set {
            this.lang1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class ude {
    
    private map[] mapField;
    
    private string nameField;
    
    private string baseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("map")]
    public map[] map {
        get {
            return this.mapField;
        }
        set {
            this.mapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class map {
    
    private string unicodeField;
    
    private string codeField;
    
    private string entField;
    
    private string substField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unicode {
        get {
            return this.unicodeField;
        }
        set {
            this.unicodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ent {
        get {
            return this.entField;
        }
        set {
            this.entField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subst {
        get {
            return this.substField;
        }
        set {
            this.substField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
public enum headerSegtype {
    
    /// <remarks/>
    block,
    
    /// <remarks/>
    paragraph,
    
    /// <remarks/>
    sentence,
    
    /// <remarks/>
    phrase,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class tu {
    
    private object[] itemsField;
    
    private tuv[] tuvField;
    
    private string tuidField;
    
    private string oencodingField;
    
    private string datatypeField;
    
    private string usagecountField;
    
    private string lastusagedateField;
    
    private string creationtoolField;
    
    private string creationtoolversionField;
    
    private string creationdateField;
    
    private string creationidField;
    
    private string changedateField;
    
    private tuSegtype segtypeField;
    
    private bool segtypeFieldSpecified;
    
    private string changeidField;
    
    private string otmfField;
    
    private string srclangField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note", typeof(note))]
    [System.Xml.Serialization.XmlElementAttribute("prop", typeof(prop))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tuv")]
    public tuv[] tuv {
        get {
            return this.tuvField;
        }
        set {
            this.tuvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tuid {
        get {
            return this.tuidField;
        }
        set {
            this.tuidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-encoding")]
    public string oencoding {
        get {
            return this.oencodingField;
        }
        set {
            this.oencodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usagecount {
        get {
            return this.usagecountField;
        }
        set {
            this.usagecountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastusagedate {
        get {
            return this.lastusagedateField;
        }
        set {
            this.lastusagedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationtool {
        get {
            return this.creationtoolField;
        }
        set {
            this.creationtoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationtoolversion {
        get {
            return this.creationtoolversionField;
        }
        set {
            this.creationtoolversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationdate {
        get {
            return this.creationdateField;
        }
        set {
            this.creationdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationid {
        get {
            return this.creationidField;
        }
        set {
            this.creationidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changedate {
        get {
            return this.changedateField;
        }
        set {
            this.changedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public tuSegtype segtype {
        get {
            return this.segtypeField;
        }
        set {
            this.segtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool segtypeSpecified {
        get {
            return this.segtypeFieldSpecified;
        }
        set {
            this.segtypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changeid {
        get {
            return this.changeidField;
        }
        set {
            this.changeidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-tmf")]
    public string otmf {
        get {
            return this.otmfField;
        }
        set {
            this.otmfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string srclang {
        get {
            return this.srclangField;
        }
        set {
            this.srclangField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class tuv {
    
    private object[] itemsField;
    
    private seg segField;
    
    private string langField;
    
    private string oencodingField;
    
    private string datatypeField;
    
    private string usagecountField;
    
    private string lastusagedateField;
    
    private string creationtoolField;
    
    private string creationtoolversionField;
    
    private string creationdateField;
    
    private string creationidField;
    
    private string changedateField;
    
    private string otmfField;
    
    private string changeidField;
    
    private string lang1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note", typeof(note))]
    [System.Xml.Serialization.XmlElementAttribute("prop", typeof(prop))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public seg seg {
        get {
            return this.segField;
        }
        set {
            this.segField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-encoding")]
    public string oencoding {
        get {
            return this.oencodingField;
        }
        set {
            this.oencodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usagecount {
        get {
            return this.usagecountField;
        }
        set {
            this.usagecountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastusagedate {
        get {
            return this.lastusagedateField;
        }
        set {
            this.lastusagedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationtool {
        get {
            return this.creationtoolField;
        }
        set {
            this.creationtoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationtoolversion {
        get {
            return this.creationtoolversionField;
        }
        set {
            this.creationtoolversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationdate {
        get {
            return this.creationdateField;
        }
        set {
            this.creationdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creationid {
        get {
            return this.creationidField;
        }
        set {
            this.creationidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changedate {
        get {
            return this.changedateField;
        }
        set {
            this.changedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("o-tmf")]
    public string otmf {
        get {
            return this.otmfField;
        }
        set {
            this.otmfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changeid {
        get {
            return this.changeidField;
        }
        set {
            this.changeidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("lang")]
    public string lang1 {
        get {
            return this.lang1Field;
        }
        set {
            this.lang1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class seg {
    
    private object[] itemsField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bpt", typeof(bpt))]
    [System.Xml.Serialization.XmlElementAttribute("ept", typeof(ept))]
    [System.Xml.Serialization.XmlElementAttribute("hi", typeof(hi))]
    [System.Xml.Serialization.XmlElementAttribute("it", typeof(it))]
    [System.Xml.Serialization.XmlElementAttribute("ph", typeof(ph))]
    [System.Xml.Serialization.XmlElementAttribute("ut", typeof(ut))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class bpt {
    
    private sub[] itemsField;
    
    private string[] textField;
    
    private string iField;
    
    private string xField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub")]
    public sub[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class sub {
    
    private object[] itemsField;
    
    private string[] textField;
    
    private string datatypeField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bpt", typeof(bpt))]
    [System.Xml.Serialization.XmlElementAttribute("ept", typeof(ept))]
    [System.Xml.Serialization.XmlElementAttribute("hi", typeof(hi))]
    [System.Xml.Serialization.XmlElementAttribute("it", typeof(it))]
    [System.Xml.Serialization.XmlElementAttribute("ph", typeof(ph))]
    [System.Xml.Serialization.XmlElementAttribute("ut", typeof(ut))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datatype {
        get {
            return this.datatypeField;
        }
        set {
            this.datatypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class ept {
    
    private sub[] itemsField;
    
    private string[] textField;
    
    private string iField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub")]
    public sub[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class hi {
    
    private object[] itemsField;
    
    private string[] textField;
    
    private string xField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bpt", typeof(bpt))]
    [System.Xml.Serialization.XmlElementAttribute("ept", typeof(ept))]
    [System.Xml.Serialization.XmlElementAttribute("hi", typeof(hi))]
    [System.Xml.Serialization.XmlElementAttribute("it", typeof(it))]
    [System.Xml.Serialization.XmlElementAttribute("ph", typeof(ph))]
    [System.Xml.Serialization.XmlElementAttribute("ut", typeof(ut))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class it {
    
    private sub[] itemsField;
    
    private string[] textField;
    
    private itPos posField;
    
    private string xField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub")]
    public sub[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public itPos pos {
        get {
            return this.posField;
        }
        set {
            this.posField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
public enum itPos {
    
    /// <remarks/>
    begin,
    
    /// <remarks/>
    end,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class ph {
    
    private sub[] itemsField;
    
    private string[] textField;
    
    private string xField;
    
    private string assocField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub")]
    public sub[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string assoc {
        get {
            return this.assocField;
        }
        set {
            this.assocField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class ut {
    
    private sub[] itemsField;
    
    private string[] textField;
    
    private string xField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub")]
    public sub[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
public enum tuSegtype {
    
    /// <remarks/>
    block,
    
    /// <remarks/>
    paragraph,
    
    /// <remarks/>
    sentence,
    
    /// <remarks/>
    phrase,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/tmx14")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/tmx14", IsNullable=false)]
public partial class body {
    
    private tu[] tuField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tu")]
    public tu[] tu {
        get {
            return this.tuField;
        }
        set {
            this.tuField = value;
        }
    }
}
